### PR TITLE
TabFunction: Added optional interpolation type argument

### PR DESCRIPTION
**Pull request by mspraggs**
This could be useful for checking systematic errors arising from various interpolation methods.

### CODE REVIEW

**Comment by aportelli** [comment]
Dear Matt,

Thank you very much this looks quite nice. Just two questions:
What is exactly your definition of quadratic interpolation: each triplet of point is joined by the associated Lagrange parabola?
What test have you performed to check that the quadratic interpolation does what we think it does?

**Comment by mspraggs** [comment]
That's what I've done yes: put a parabola through the nearest three points, then use that parabola to determine the value at the specified x. I don't think this code is particularly performant. I know the GSL has a polynomial interpolation function for arbitrary order, but I thought I'd write my own in this case.

I haven't tested it thoroughly. I have run the g - 2 code with it and the nearest, linear and quadratic interpolated values come out pretty much identical. Yes in principle it would be a good idea to add an example to test this. I could potentially knock up a quick example to check it works.

**Comment by aportelli** [comment]
Ok great. Just do a quick check that this is indeed the quadratic Lagrange interpolation of the 3 points and I will merge it if things are ok. You could include that in the plot example that I used to check the linear interpolation.

**Comment by mspraggs** [comment]
Just as well I wrote an example! Found a bug: was checking the nearest `it` variable against `value_.end()`, not the iterator pointing to the last element of `value_`.

EDIT: Should mention I fixed this, so I think it's ready to go.

**Pull request merged**
