### PR TITLE
Utils: Added little utility to flatten 1x1 DMatSamples

### PR DESCRIPTION
**Pull request by mspraggs**
'cause, y'know, it's handy now the file formats have changed a bit.

### CODE REVIEW

**Comment by aportelli** [comment]
I have a proposition: the old LatAnalyze had a useful CL tool to get a component of a sample which is a rather trivial generalisation of what you propose. We could call it `latan_sample_element` and it would be used like:

```
latan_sample_element foo.h5 2 3 bar.h5
```

which takes the line 2 and column 3 from `foo.h5`, print on screen the central value and the error (identically to `latan_sample_read` & cie) and save it as a `DSample` in `bar.h5` (this argument would be optional as in `latan_sample_read`). So your current program would become:

```
latan_sample_element foo.h5 0 0 bar.h5
```

How does that sound?

**Comment by mspraggs** [comment]
Sure, sounds good, and as you say should be easy to adapt the program I've implemented.

**Comment by mspraggs** [comment]
Just bumping this, as I've submitted the suggested modifications.

**Comment by aportelli** [comment]
Ok thanks! I will include it in the v3.2 that I am currently preparing. Beware that it will be renamed `latan-sample-element`.

**Comment by aportelli** [comment]
Wait there is a conflict, but this is my fault I'll deal with it.

**Pull request merged**
